SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;


CREATE TABLE moz70_unicornr_account (
  id int(10) UNSIGNED NOT NULL,
  state tinyint(1) NOT NULL DEFAULT 1,
  ordering int(11) NOT NULL DEFAULT 0,
  checked_out int(11) NOT NULL DEFAULT 0,
  checked_out_time datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  created_by int(11) NOT NULL DEFAULT 0,
  modified_by int(11) NOT NULL DEFAULT 0,
  custom_field1 varchar(255) NOT NULL DEFAULT '',
  custom_field2 varchar(255) NOT NULL DEFAULT '',
  custom_field3 varchar(255) NOT NULL DEFAULT '',
  custom_field4 varchar(255) NOT NULL DEFAULT '',
  custom_field5 varchar(255) NOT NULL DEFAULT '',
  custom_field6 varchar(255) NOT NULL DEFAULT '',
  custom_field7 varchar(255) NOT NULL DEFAULT '',
  custom_field8 varchar(255) NOT NULL DEFAULT '',
  custom_field9 varchar(255) NOT NULL DEFAULT '',
  custom_field10 varchar(255) NOT NULL DEFAULT '',
  user int(11) NOT NULL,
  access_company text NOT NULL,
  access_time_from datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  access_time_to datetime NOT NULL DEFAULT '0000-00-00 00:00:00'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE moz70_unicornr_address (
  id int(10) UNSIGNED NOT NULL,
  state tinyint(1) NOT NULL DEFAULT 1,
  ordering int(11) NOT NULL DEFAULT 0,
  checked_out int(11) NOT NULL DEFAULT 0,
  checked_out_time datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  created_by int(11) NOT NULL DEFAULT 0,
  modified_by int(11) NOT NULL DEFAULT 0,
  clientcode varchar(255) NOT NULL DEFAULT '',
  setorder int(11) NOT NULL DEFAULT 0,
  addrtype varchar(255) NOT NULL DEFAULT '',
  add1 longtext NOT NULL,
  add2 longtext NOT NULL,
  add3 longtext NOT NULL,
  postcode varchar(255) NOT NULL DEFAULT '',
  town varchar(255) NOT NULL DEFAULT '',
  addstate varchar(255) NOT NULL DEFAULT '',
  countryid varchar(255) NOT NULL DEFAULT '',
  tel varchar(255) NOT NULL DEFAULT '',
  fax varchar(255) NOT NULL DEFAULT '',
  email varchar(255) NOT NULL DEFAULT '',
  webmail varchar(255) NOT NULL DEFAULT '',
  sameas varchar(255) NOT NULL DEFAULT '',
  doeff date NOT NULL DEFAULT '0000-00-00',
  docease date NOT NULL DEFAULT '0000-00-00',
  closure varchar(255) NOT NULL DEFAULT '',
  stime varchar(255) NOT NULL DEFAULT '',
  etime varchar(255) NOT NULL DEFAULT '',
  donotice date NOT NULL DEFAULT '0000-00-00',
  mustmember varchar(255) NOT NULL DEFAULT '',
  lresomem varchar(255) NOT NULL DEFAULT '',
  chgfrid int(11) NOT NULL DEFAULT 0,
  priority varchar(255) NOT NULL DEFAULT '',
  eventcode varchar(255) NOT NULL DEFAULT '',
  `desc` longtext NOT NULL,
  desc1 longtext NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE moz70_unicornr_file (
  id int(10) UNSIGNED NOT NULL,
  state tinyint(1) NOT NULL DEFAULT 1,
  ordering int(11) NOT NULL DEFAULT 0,
  checked_out int(11) NOT NULL DEFAULT 0,
  checked_out_time datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  created_by int(11) NOT NULL DEFAULT 0,
  modified_by int(11) NOT NULL DEFAULT 0,
  custom_field1 varchar(255) NOT NULL DEFAULT '',
  custom_field2 varchar(255) NOT NULL DEFAULT '',
  custom_field3 varchar(255) NOT NULL DEFAULT '',
  custom_field4 varchar(255) NOT NULL DEFAULT '',
  custom_field5 varchar(255) NOT NULL DEFAULT '',
  filename varchar(255) NOT NULL DEFAULT '',
  created_date datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  created_year varchar(255) NOT NULL DEFAULT '',
  filetype varchar(255) DEFAULT NULL,
  transaction_id text DEFAULT NULL,
  form_type varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE moz70_unicornr_history_logs (
  id int(10) UNSIGNED NOT NULL,
  state tinyint(1) NOT NULL DEFAULT 1,
  ordering int(11) NOT NULL DEFAULT 0,
  checked_out int(11) NOT NULL DEFAULT 0,
  checked_out_time datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  created_by int(11) NOT NULL DEFAULT 0,
  modified_by int(11) NOT NULL DEFAULT 0,
  custom_field1 varchar(255) NOT NULL DEFAULT '',
  custom_field2 varchar(255) NOT NULL DEFAULT '',
  custom_field3 varchar(255) NOT NULL DEFAULT '',
  custom_field4 varchar(255) NOT NULL DEFAULT '',
  custom_field5 varchar(255) NOT NULL DEFAULT '',
  logdata varchar(255) NOT NULL DEFAULT '',
  createdby int(11) NOT NULL DEFAULT 0,
  createddate datetime NOT NULL DEFAULT '0000-00-00 00:00:00'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE moz70_unicornr_table_allot (
  id int(10) UNSIGNED NOT NULL,
  state tinyint(1) NOT NULL DEFAULT 1,
  ordering int(11) NOT NULL DEFAULT 0,
  checked_out int(11) NOT NULL DEFAULT 0,
  checked_out_time datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  created_by int(11) NOT NULL DEFAULT 0,
  modified_by int(11) NOT NULL DEFAULT 0,
  userid varchar(255) NOT NULL DEFAULT '',
  custom_field1 varchar(255) NOT NULL DEFAULT '',
  custom_field2 varchar(255) NOT NULL DEFAULT '',
  custom_field3 varchar(255) NOT NULL DEFAULT '',
  custom_field4 varchar(255) NOT NULL DEFAULT '',
  custom_field5 varchar(255) NOT NULL DEFAULT '',
  clientcode varchar(255) NOT NULL DEFAULT '',
  allotno varchar(255) NOT NULL DEFAULT '',
  doallot datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  posttype varchar(255) NOT NULL DEFAULT '',
  eventcode varchar(255) NOT NULL DEFAULT '',
  bdate datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  bratio varchar(255) NOT NULL DEFAULT '',
  bpershare varchar(255) NOT NULL DEFAULT '',
  btype varchar(255) NOT NULL DEFAULT '',
  c11 varchar(255) NOT NULL DEFAULT '',
  c12 varchar(255) NOT NULL DEFAULT '',
  c13 varchar(255) NOT NULL DEFAULT '',
  c2 varchar(255) NOT NULL DEFAULT '',
  c21 varchar(255) NOT NULL DEFAULT '',
  c22 varchar(255) NOT NULL DEFAULT '',
  c3 varchar(255) NOT NULL DEFAULT '',
  c31 varchar(255) NOT NULL DEFAULT '',
  c32 varchar(255) NOT NULL DEFAULT '',
  c4 varchar(255) NOT NULL DEFAULT '',
  datechg datetime NOT NULL DEFAULT '0000-00-00 00:00:00'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE moz70_unicornr_table_clientdata (
  id int(10) UNSIGNED NOT NULL,
  state tinyint(1) NOT NULL DEFAULT 1,
  ordering int(11) NOT NULL DEFAULT 0,
  checked_out int(11) NOT NULL DEFAULT 0,
  checked_out_time datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  created_by int(11) NOT NULL DEFAULT 0,
  modified_by int(11) NOT NULL DEFAULT 0,
  custom_field1 varchar(155) NOT NULL DEFAULT '',
  custom_field2 varchar(155) NOT NULL DEFAULT '',
  custom_field3 varchar(155) NOT NULL DEFAULT '',
  custom_field4 varchar(155) NOT NULL DEFAULT '',
  custom_field5 varchar(155) NOT NULL DEFAULT '',
  clientcode varchar(155) NOT NULL DEFAULT '',
  refno varchar(155) NOT NULL DEFAULT '',
  name varchar(155) NOT NULL DEFAULT '',
  comno varchar(155) NOT NULL DEFAULT '',
  comno_old varchar(155) NOT NULL DEFAULT '',
  gstno varchar(155) NOT NULL DEFAULT '',
  doformer datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  formername varchar(155) NOT NULL DEFAULT '',
  doi varchar(155) NOT NULL DEFAULT '',
  countryi varchar(255) DEFAULT NULL,
  curr varchar(255) DEFAULT NULL,
  capital int(11) DEFAULT NULL,
  capitalp int(11) DEFAULT NULL,
  capitalk int(11) DEFAULT NULL,
  parvalue int(11) DEFAULT NULL,
  paidcapc varchar(155) NOT NULL DEFAULT '',
  paidcapn varchar(155) NOT NULL DEFAULT '',
  paidcap varchar(155) NOT NULL DEFAULT '',
  paidcapp varchar(155) NOT NULL DEFAULT '',
  paidcapk varchar(155) NOT NULL DEFAULT '',
  sharesc varchar(155) NOT NULL DEFAULT '',
  sharesn varchar(155) NOT NULL DEFAULT '',
  shareso varchar(155) NOT NULL DEFAULT '',
  sharesp varchar(155) NOT NULL DEFAULT '',
  sharesk varchar(155) NOT NULL DEFAULT '',
  lcallup varchar(155) NOT NULL DEFAULT '',
  callupo varchar(155) NOT NULL DEFAULT '',
  callupp varchar(155) NOT NULL DEFAULT '',
  callupk varchar(155) NOT NULL DEFAULT '',
  status varchar(155) NOT NULL DEFAULT '',
  taxagent varchar(155) NOT NULL DEFAULT '',
  auditor varchar(155) NOT NULL DEFAULT '',
  yearend datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  accdead datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  lastagm datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  lastar datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  lastac datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  agmdead datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  lallotno varchar(155) NOT NULL DEFAULT '',
  ltranno varchar(155) NOT NULL DEFAULT '',
  lcertno varchar(155) NOT NULL DEFAULT '',
  lsplitno varchar(155) NOT NULL DEFAULT '',
  llostno varchar(155) NOT NULL DEFAULT '',
  lconno varchar(155) NOT NULL DEFAULT '',
  lresono varchar(155) NOT NULL DEFAULT '',
  ldivno varchar(155) NOT NULL DEFAULT '',
  lredeemno varchar(155) NOT NULL DEFAULT '',
  lsubdivno varchar(155) NOT NULL DEFAULT '',
  workday varchar(155) NOT NULL DEFAULT '',
  workhour varchar(155) NOT NULL DEFAULT '',
  contact varchar(155) NOT NULL DEFAULT '',
  tel varchar(155) NOT NULL DEFAULT '',
  fax varchar(155) NOT NULL DEFAULT '',
  email varchar(155) NOT NULL DEFAULT '',
  comptype varchar(155) NOT NULL DEFAULT '',
  compstatus varchar(155) NOT NULL DEFAULT '',
  compseal varchar(155) NOT NULL DEFAULT '',
  doapp datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  docease datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  dolisted datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  dosubmit datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  doroclet datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  dorocnoti datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  dorocnoti4 datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  dogaz datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  dowstart datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  dowfinal datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  dissolved datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  comphold varchar(155) NOT NULL DEFAULT '',
  repcode varchar(155) NOT NULL DEFAULT '',
  compgroup varchar(155) NOT NULL DEFAULT '',
  compattrib varchar(155) NOT NULL DEFAULT '',
  compfee varchar(155) NOT NULL DEFAULT '',
  feetype varchar(155) NOT NULL DEFAULT '',
  bill_day varchar(155) NOT NULL DEFAULT '',
  bill_mth varchar(155) NOT NULL DEFAULT '',
  accno varchar(155) NOT NULL DEFAULT '',
  buscode1 varchar(155) NOT NULL DEFAULT '',
  buscode2 varchar(155) NOT NULL DEFAULT '',
  buscode3 varchar(155) NOT NULL DEFAULT '',
  com varchar(155) NOT NULL DEFAULT '',
  cob varchar(155) NOT NULL DEFAULT '',
  dirsign varchar(155) NOT NULL DEFAULT '',
  mdirector varchar(155) NOT NULL DEFAULT '',
  seccode varchar(155) NOT NULL DEFAULT '',
  sharecert varchar(155) NOT NULL DEFAULT '',
  doapprove varchar(155) NOT NULL DEFAULT '',
  approvalno varchar(155) NOT NULL DEFAULT '',
  roccode varchar(155) NOT NULL DEFAULT '',
  lodger varchar(155) NOT NULL DEFAULT '',
  feecode varchar(155) NOT NULL DEFAULT '',
  jurisdict varchar(155) NOT NULL DEFAULT '',
  chqno varchar(155) NOT NULL DEFAULT '',
  posttype varchar(155) NOT NULL DEFAULT '',
  datechg datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  userid int(11) NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE moz70_unicornr_table_member (
  id int(10) UNSIGNED NOT NULL,
  state tinyint(1) NOT NULL DEFAULT 1,
  ordering int(11) NOT NULL DEFAULT 0,
  checked_out int(11) NOT NULL DEFAULT 0,
  checked_out_time datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  created_by int(11) NOT NULL DEFAULT 0,
  modified_by int(11) NOT NULL DEFAULT 0,
  userid varchar(255) NOT NULL DEFAULT '',
  custom_field1 varchar(255) NOT NULL DEFAULT '',
  custom_field2 varchar(255) NOT NULL DEFAULT '',
  custom_field3 varchar(255) NOT NULL DEFAULT '',
  custom_field4 varchar(255) NOT NULL DEFAULT '',
  custom_field5 varchar(255) NOT NULL DEFAULT '',
  code varchar(255) NOT NULL DEFAULT '',
  name varchar(255) NOT NULL DEFAULT '',
  formername varchar(255) NOT NULL DEFAULT '',
  doformer datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  idtype varchar(255) NOT NULL DEFAULT '',
  icno varchar(255) NOT NULL DEFAULT '',
  oldicno varchar(255) NOT NULL DEFAULT '',
  iccolor varchar(255) NOT NULL DEFAULT '',
  passport varchar(255) NOT NULL DEFAULT '',
  passtype varchar(255) NOT NULL DEFAULT '',
  passissue varchar(255) NOT NULL DEFAULT '',
  passexpire datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  emppass varchar(255) NOT NULL DEFAULT '',
  depenpass varchar(255) NOT NULL DEFAULT '',
  empexpire datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  occupation varchar(255) NOT NULL DEFAULT '',
  sex varchar(255) NOT NULL DEFAULT '',
  local_resaddr varchar(255) NOT NULL,
  race varchar(255) NOT NULL DEFAULT '',
  add1 varchar(255) NOT NULL DEFAULT '',
  add2 varchar(255) NOT NULL DEFAULT '',
  add3 varchar(255) NOT NULL DEFAULT '',
  postcode varchar(255) NOT NULL DEFAULT '',
  town varchar(255) NOT NULL DEFAULT '',
  mem_state varchar(255) NOT NULL,
  countryid varchar(255) NOT NULL DEFAULT '',
  tel varchar(255) NOT NULL DEFAULT '',
  hphone varchar(255) NOT NULL DEFAULT '',
  email varchar(255) NOT NULL DEFAULT '',
  lhideeml varchar(255) NOT NULL DEFAULT '',
  srv_add1 varchar(255) NOT NULL DEFAULT '',
  srv_add2 varchar(255) NOT NULL DEFAULT '',
  srv_add3 varchar(255) NOT NULL DEFAULT '',
  srv_post varchar(255) NOT NULL DEFAULT '',
  srv_town varchar(255) NOT NULL DEFAULT '',
  srv_state varchar(255) NOT NULL DEFAULT '',
  srv_countryid varchar(255) NOT NULL DEFAULT '',
  local_busaddr varchar(255) NOT NULL,
  bus_add1 varchar(255) NOT NULL,
  bus_add2 varchar(255) NOT NULL,
  bus_add3 varchar(255) NOT NULL,
  bus_post varchar(255) NOT NULL,
  bus_town varchar(255) NOT NULL,
  bus_state varchar(255) NOT NULL,
  bus_countryid varchar(255) NOT NULL,
  d_town varchar(255) NOT NULL DEFAULT '',
  d_state varchar(255) NOT NULL DEFAULT '',
  title varchar(255) NOT NULL DEFAULT '',
  nationcode varchar(255) NOT NULL DEFAULT '',
  citizenship varchar(255) NOT NULL,
  dob datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  ydob varchar(255) NOT NULL DEFAULT '',
  malaysian varchar(255) NOT NULL DEFAULT '',
  shareheld int(11) NOT NULL DEFAULT 0,
  repcode varchar(255) NOT NULL DEFAULT '',
  memtype varchar(255) NOT NULL DEFAULT '',
  regtype varchar(255) NOT NULL DEFAULT '',
  inactive varchar(255) NOT NULL DEFAULT '',
  pracertno varchar(255) NOT NULL DEFAULT '',
  lictype varchar(255) NOT NULL DEFAULT '',
  license varchar(255) NOT NULL DEFAULT '',
  licenseexp datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  licenseisu datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  issec varchar(255) NOT NULL DEFAULT '',
  datechg datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  dgtcertexp varchar(255) NOT NULL,
  pracertexp text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE moz70_unicornr_table_member_backup (
  id int(10) UNSIGNED NOT NULL DEFAULT 0,
  state tinyint(1) NOT NULL DEFAULT 1,
  ordering int(11) NOT NULL DEFAULT 0,
  checked_out int(11) NOT NULL DEFAULT 0,
  checked_out_time datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  created_by int(11) NOT NULL DEFAULT 0,
  modified_by int(11) NOT NULL DEFAULT 0,
  userid varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  custom_field1 varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  custom_field2 varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  custom_field3 varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  custom_field4 varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  custom_field5 varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  code varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  name varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  formername varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  doformer datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  idtype varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  icno varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  oldicno varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  iccolor varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  passport varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  passtype varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  passissue varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  passexpire datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  emppass varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  depenpass varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  empexpire datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  occupation varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  sex varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  race varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  add1 varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  add2 varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  add3 varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  postcode varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  town varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  mem_state varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  countryid varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  tel varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  hphone varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  email varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  lhideeml varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  srv_add1 varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  srv_add2 varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  srv_add3 varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  srv_post varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  srv_town varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  srv_state varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  srv_countryid varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  d_town varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  d_state varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  title varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  nationcode varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  dob datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  ydob varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  malaysian varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  shareheld int(11) NOT NULL DEFAULT 0,
  repcode varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  memtype varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  regtype varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  inactive varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  pracertno varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  lictype varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  license varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  licenseexp datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  licenseisu datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  issec varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  datechg datetime NOT NULL DEFAULT '0000-00-00 00:00:00'
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

CREATE TABLE moz70_unicornr_table_regdir (
  id int(10) UNSIGNED NOT NULL,
  state tinyint(1) NOT NULL DEFAULT 1,
  ordering int(11) NOT NULL DEFAULT 0,
  checked_out int(11) NOT NULL DEFAULT 0,
  checked_out_time datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  created_by int(11) NOT NULL DEFAULT 0,
  modified_by int(11) NOT NULL DEFAULT 0,
  userid varchar(255) NOT NULL DEFAULT '',
  custom_field1 varchar(255) NOT NULL DEFAULT '',
  custom_field2 varchar(255) NOT NULL DEFAULT '',
  custom_field3 varchar(255) NOT NULL DEFAULT '',
  custom_field4 varchar(255) NOT NULL DEFAULT '',
  custom_field5 varchar(255) NOT NULL DEFAULT '',
  clientcode varchar(255) NOT NULL DEFAULT '',
  dircode varchar(255) NOT NULL DEFAULT '',
  doapp datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  docease datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  natureapp varchar(255) NOT NULL DEFAULT '',
  setorder int(11) NOT NULL DEFAULT 0,
  alttodir varchar(255) NOT NULL DEFAULT '',
  kin varchar(255) NOT NULL DEFAULT '',
  docusign varchar(255) NOT NULL DEFAULT '',
  occupation varchar(255) NOT NULL DEFAULT '',
  nxtdoapp datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  doremind datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  datechg datetime NOT NULL DEFAULT '0000-00-00 00:00:00'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE moz70_unicornr_table_regmem (
  id int(10) UNSIGNED NOT NULL,
  state tinyint(1) NOT NULL DEFAULT 1,
  ordering int(11) NOT NULL DEFAULT 0,
  checked_out int(11) NOT NULL DEFAULT 0,
  checked_out_time datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  created_by int(11) NOT NULL DEFAULT 0,
  modified_by int(11) NOT NULL DEFAULT 0,
  userid varchar(255) NOT NULL DEFAULT '',
  custom_field1 varchar(255) NOT NULL DEFAULT '',
  custom_field2 varchar(255) NOT NULL DEFAULT '',
  custom_field3 varchar(255) NOT NULL DEFAULT '',
  custom_field4 varchar(255) NOT NULL DEFAULT '',
  custom_field5 varchar(255) NOT NULL DEFAULT '',
  clientcode varchar(255) NOT NULL DEFAULT '',
  memcode varchar(255) NOT NULL DEFAULT '',
  doapp datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  docease datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  natureapp varchar(255) NOT NULL DEFAULT '',
  setorder int(11) NOT NULL DEFAULT 0,
  folio varchar(255) NOT NULL DEFAULT '',
  repcode varchar(255) NOT NULL DEFAULT '',
  occupation varchar(255) NOT NULL DEFAULT '',
  tnoshares varchar(255) NOT NULL DEFAULT '',
  percent varchar(255) NOT NULL DEFAULT '',
  tnosharesp varchar(255) NOT NULL DEFAULT '',
  percentp varchar(255) NOT NULL DEFAULT '',
  tnosharesk varchar(255) NOT NULL DEFAULT '',
  percentk varchar(255) NOT NULL DEFAULT '',
  trusttype varchar(255) NOT NULL DEFAULT '',
  memship varchar(255) NOT NULL DEFAULT '',
  amount varchar(255) NOT NULL DEFAULT '',
  datechg datetime NOT NULL DEFAULT '0000-00-00 00:00:00'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE moz70_unicornr_table_shares (
  id int(10) UNSIGNED NOT NULL,
  state tinyint(1) NOT NULL DEFAULT 1,
  ordering int(11) NOT NULL DEFAULT 0,
  checked_out int(11) NOT NULL DEFAULT 0,
  checked_out_time datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  created_by int(11) NOT NULL DEFAULT 0,
  modified_by int(11) NOT NULL DEFAULT 0,
  custom_field1 varchar(255) NOT NULL DEFAULT '',
  custom_field2 varchar(255) NOT NULL DEFAULT '',
  custom_field3 varchar(255) NOT NULL DEFAULT '',
  custom_field4 varchar(255) NOT NULL DEFAULT '',
  custom_field5 varchar(255) NOT NULL DEFAULT '',
  clientcode varchar(255) NOT NULL DEFAULT '',
  memcode varchar(255) NOT NULL DEFAULT '',
  tranno varchar(255) NOT NULL DEFAULT '',
  trandate datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  trantype varchar(255) NOT NULL DEFAULT '',
  btype varchar(255) NOT NULL DEFAULT '',
  frcertno varchar(255) NOT NULL DEFAULT '',
  tocertno varchar(255) NOT NULL DEFAULT '',
  certno varchar(255) NOT NULL DEFAULT '',
  sharecls varchar(255) NOT NULL DEFAULT '',
  sharecat varchar(255) NOT NULL DEFAULT '',
  sharetype varchar(255) NOT NULL DEFAULT '',
  shareheld varchar(255) NOT NULL DEFAULT '',
  certtype varchar(255) NOT NULL DEFAULT '',
  noshare varchar(255) NOT NULL DEFAULT '',
  sharevalue varchar(255) NOT NULL DEFAULT '',
  paidvalue varchar(255) NOT NULL DEFAULT '',
  unpaid varchar(255) NOT NULL DEFAULT '',
  premium varchar(255) NOT NULL DEFAULT '',
  memjoin varchar(255) NOT NULL DEFAULT '',
  memexe varchar(255) NOT NULL DEFAULT '',
  amount varchar(255) NOT NULL DEFAULT '',
  lastamount varchar(255) NOT NULL DEFAULT '',
  docease datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  ceasetype varchar(255) NOT NULL DEFAULT '',
  ceaseno varchar(255) NOT NULL DEFAULT '',
  posttype varchar(255) NOT NULL DEFAULT '',
  posted varchar(255) NOT NULL DEFAULT '',
  lsubdiv varchar(255) NOT NULL DEFAULT '',
  serialno varchar(255) NOT NULL DEFAULT '',
  remark text NOT NULL,
  eventcode varchar(255) NOT NULL DEFAULT '',
  datechg datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  userid int(11) NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE moz70_unicornr_table_sharetp (
  id int(10) UNSIGNED NOT NULL,
  state tinyint(1) NOT NULL DEFAULT 1,
  ordering int(11) NOT NULL DEFAULT 0,
  checked_out int(11) NOT NULL DEFAULT 0,
  checked_out_time datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  created_by int(11) NOT NULL DEFAULT 0,
  modified_by int(11) NOT NULL DEFAULT 0,
  userid varchar(255) NOT NULL DEFAULT '',
  custom_field1 varchar(255) NOT NULL DEFAULT '',
  custom_field2 varchar(255) NOT NULL DEFAULT '',
  custom_field3 varchar(255) NOT NULL DEFAULT '',
  custom_field4 varchar(255) NOT NULL DEFAULT '',
  custom_field5 varchar(255) NOT NULL DEFAULT '',
  sharecls varchar(255) NOT NULL DEFAULT '',
  sharedesc varchar(255) NOT NULL DEFAULT '',
  category int(11) NOT NULL DEFAULT 0,
  inactive varchar(255) NOT NULL DEFAULT '',
  datechg datetime NOT NULL DEFAULT '0000-00-00 00:00:00'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE moz70_unicornr_table_split (
  id int(10) UNSIGNED NOT NULL,
  state tinyint(1) NOT NULL DEFAULT 1,
  ordering int(11) NOT NULL DEFAULT 0,
  checked_out int(11) NOT NULL DEFAULT 0,
  checked_out_time datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  created_by int(11) NOT NULL DEFAULT 0,
  modified_by int(11) NOT NULL DEFAULT 0,
  userid varchar(255) NOT NULL DEFAULT '',
  custom_field1 varchar(255) NOT NULL DEFAULT '',
  custom_field2 varchar(255) NOT NULL DEFAULT '',
  custom_field3 varchar(255) NOT NULL DEFAULT '',
  custom_field4 varchar(255) NOT NULL DEFAULT '',
  custom_field5 varchar(255) NOT NULL DEFAULT '',
  clientcode varchar(255) NOT NULL DEFAULT '',
  splitno varchar(255) NOT NULL DEFAULT '',
  dosplit datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  certno varchar(255) NOT NULL DEFAULT '',
  memcode varchar(255) NOT NULL DEFAULT '',
  noshare varchar(255) NOT NULL DEFAULT '',
  amount varchar(255) NOT NULL DEFAULT '',
  datechg datetime NOT NULL DEFAULT '0000-00-00 00:00:00'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE moz70_unicornr_table_state (
  id int(10) UNSIGNED NOT NULL,
  state tinyint(1) NOT NULL DEFAULT 1,
  ordering int(11) NOT NULL DEFAULT 0,
  checked_out int(11) NOT NULL DEFAULT 0,
  checked_out_time datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  created_by int(11) NOT NULL DEFAULT 0,
  modified_by int(11) NOT NULL DEFAULT 0,
  userid varchar(255) NOT NULL DEFAULT '',
  custom_field1 varchar(255) NOT NULL DEFAULT '',
  custom_field2 varchar(255) NOT NULL DEFAULT '',
  custom_field3 varchar(255) NOT NULL DEFAULT '',
  custom_field4 varchar(255) NOT NULL DEFAULT '',
  custom_field5 varchar(255) NOT NULL DEFAULT '',
  code varchar(255) NOT NULL DEFAULT '',
  state_copy_1 varchar(255) NOT NULL,
  act varchar(255) NOT NULL DEFAULT '',
  datechg datetime NOT NULL DEFAULT '0000-00-00 00:00:00'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE moz70_unicornr_transaction (
  id int(10) UNSIGNED NOT NULL,
  state tinyint(1) NOT NULL DEFAULT 1,
  ordering int(11) NOT NULL DEFAULT 0,
  checked_out int(11) NOT NULL DEFAULT 0,
  checked_out_time datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  created_by int(11) NOT NULL DEFAULT 0,
  modified_by int(11) NOT NULL DEFAULT 0,
  custom_field1 varchar(255) NOT NULL DEFAULT '',
  custom_field2 varchar(255) NOT NULL DEFAULT '',
  custom_field3 varchar(255) NOT NULL DEFAULT '',
  custom_field4 varchar(255) NOT NULL DEFAULT '',
  custom_field5 varchar(255) NOT NULL DEFAULT '',
  custom_field6 varchar(255) NOT NULL DEFAULT '',
  custom_field7 varchar(255) NOT NULL DEFAULT '',
  custom_field8 varchar(255) NOT NULL DEFAULT '',
  custom_field9 varchar(255) NOT NULL DEFAULT '',
  custom_field10 varchar(255) NOT NULL DEFAULT '',
  custom_field11 varchar(255) NOT NULL DEFAULT '',
  custom_field12 varchar(255) NOT NULL DEFAULT '',
  custom_field13 varchar(255) NOT NULL DEFAULT '',
  custom_field14 varchar(255) NOT NULL DEFAULT '',
  custom_field15 varchar(255) NOT NULL DEFAULT '',
  topic varchar(255) NOT NULL,
  transtype text NOT NULL,
  createddate datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  assignedcompany text NOT NULL,
  assignedmember text DEFAULT NULL,
  doreminder datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  formupload text NOT NULL,
  signbackform text NOT NULL,
  returnform text NOT NULL,
  certifiedtruecopy text NOT NULL,
  minutesbook text NOT NULL,
  transstatus text NOT NULL,
  remark text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Add notified_to_user field to transaction status log table
ALTER TABLE moz70_unicornr_transaction_status_log
  ADD COLUMN notified_to_user TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'Whether the status change has been notified to users';

CREATE TABLE moz70_unicornr_transaction_custom (
  id int(10) UNSIGNED NOT NULL,
  state tinyint(1) NOT NULL DEFAULT 1,
  ordering int(11) NOT NULL DEFAULT 0,
  checked_out int(11) NOT NULL DEFAULT 0,
  checked_out_time datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  created_by int(11) NOT NULL DEFAULT 0,
  modified_by int(11) NOT NULL DEFAULT 0,
  custom_field1 varchar(255) NOT NULL DEFAULT '',
  custom_field2 varchar(255) NOT NULL DEFAULT '',
  custom_field3 varchar(255) NOT NULL DEFAULT '',
  custom_field4 varchar(255) NOT NULL DEFAULT '',
  custom_field5 varchar(255) NOT NULL DEFAULT '',
  fieldtype varchar(255) NOT NULL,
  fielddata varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;